version: '3.9'

services:
  app:
    build: .
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: webscrap
      DB_USERNAME: root
      DB_PASSWORD: root
    command: >
      sh -c "php artisan migrate && php-fpm"

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webscrap
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
